# Generated by Django 4.2.3 on 2024-12-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0006_paciente_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rol',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('administrador', 'Administrador')], default='Paciente', max_length=20),
        ),
    ]
