# Generated by Django 4.2.3 on 2024-12-15 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalAppointment', '0009_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.CharField(default='Hospital Isidro Ayora(Matriz)', max_length=255),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.especialidad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Reservada', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
