# Generated by Django 4.2.3 on 2024-12-21 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0013_remove_medico_apellido_remove_medico_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('es_covid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='MedicalAppointment.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='MedicalAppointment.paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='reservada', max_length=50),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=255)),
                ('dosis', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=255)),
                ('prescripcion', models.TextField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='MedicalAppointment.diagnostico')),
            ],
        ),
    ]
