# Generated by Django 4.2.3 on 2024-12-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0015_alter_cita_options_cita_descripcion_cita_motivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='MedicalAppointment.paciente'),
            preserve_default=False,
        ),
    ]
