# Generated by Django 4.2.3 on 2024-12-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0016_remove_cita_usuario_cita_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='MedicalAppointment.cita')),
                ('diagnostico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.diagnostico')),
                ('receta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.receta')),
            ],
        ),
    ]
