# Generated by Django 4.2.3 on 2024-12-21 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0018_enfermedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='receta',
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='medicamentos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='tipo_enfermedad',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='diagnostico',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
