# Generated by Django 4.2.3 on 2024-12-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0019_remove_fichamedica_receta_fichamedica_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='tipo_enfermedad',
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='diagnostico',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='medicamentos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
