# Generated by Django 4.2.3 on 2024-12-21 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalAppointment', '0020_remove_fichamedica_tipo_enfermedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='tipo_enfermedad',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.paciente'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='MedicalAppointment.diagnostico'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='medicamentos',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
