# Generated by Django 4.2.3 on 2024-12-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('MedicalAppointment', '0021_fichamedica_tipo_enfermedad_alter_diagnostico_medico_and_more'),
    ]

    operations = [
        # Eliminar campos de FichaMedica y Receta
        migrations.RemoveField(
            model_name='fichamedica',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='nombre_medicamento',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='prescripcion',
        ),

        # Agregar nuevos campos
        migrations.AddField(
            model_name='fichamedica',
            name='receta',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='MedicalAppointment.receta',
                null=True,  # Permitir valores nulos para evitar errores durante la migración
            ),
        ),
        migrations.AddField(
            model_name='receta',
            name='cita',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='MedicalAppointment.cita',
                null=True,  # Permitir valores nulos temporalmente
            ),
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='medicamentos',
            field=models.JSONField(default=dict),  # Cambiar el valor predeterminado a un JSON válido
        ),
        migrations.AddField(
            model_name='receta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
