# Generated by Django 4.2.3 on 2024-12-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0022_remove_fichamedica_medicamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='notas',
        ),
        migrations.AddField(
            model_name='receta',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='MedicalAppointment.diagnostico'),
        ),
        migrations.AddField(
            model_name='receta',
            name='dosis',
            field=models.CharField(blank=True, default='No especificada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='duracion',
            field=models.CharField(blank=True, default='No especificada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombre_medicamento',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='prescripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
