# Generated by Django 4.2.3 on 2024-12-22 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0023_remove_receta_cita_remove_receta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
