# Generated by Django 4.2.3 on 2024-12-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0024_receta_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='MedicalAppointment.diagnostico'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.receta'),
        ),
    ]
