# Generated by Django 4.2.3 on 2024-12-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0028_alter_fichamedica_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.enfermedad'),
        ),
    ]
