# Generated by Django 4.2.3 on 2024-12-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0029_diagnostico_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='diagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='MedicalAppointment.diagnostico'),
            preserve_default=False,
        ),
    ]
