# Generated by Django 4.2.3 on 2024-12-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0030_receta_notas_alter_receta_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='tipo_enfermedad',
        ),
    ]
