# Generated by Django 4.2.3 on 2024-12-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0032_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='canton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.canton'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_cedula',
            field=models.CharField(max_length=10),
        ),
    ]
