# Generated by Django 4.2.3 on 2025-01-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0033_paciente_canton_paciente_genero_paciente_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='calificacion',
            field=models.IntegerField(blank=True, help_text='Calificación de la cita (1-5, solo para citas finalizadas).', null=True),
        ),
    ]
