# Generated by Django 4.2.3 on 2025-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0034_cita_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_cedula',
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], default='cedula', max_length=20),
        ),
    ]
