# Generated by Django 4.2.3 on 2025-01-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0035_remove_paciente_numero_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.CharField(blank=True, default='Ecuador', max_length=50, null=True),
        ),
    ]
