# Generated by Django 4.2.3 on 2025-01-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0036_paciente_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointment.canton'),
        ),
    ]
