# Generated by Django 4.2.3 on 2025-02-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointment', '0037_alter_paciente_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='categoria_triaje',
            field=models.CharField(choices=[('verde', 'No urgente'), ('amarillo', 'Urgente'), ('naranja', 'Muy urgente'), ('rojo', 'Emergencia')], default='verde', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='nivel_conciencia',
            field=models.CharField(blank=True, choices=[('alerta', 'Alerta'), ('voz', 'Responde a voz'), ('dolor', 'Responde al dolor'), ('no_responde', 'No responde')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='presion_arterial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='puntaje_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='saturacion_oxigeno',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
